### ISSUE TITLE
建议在说明里增加服务器状态打分的标准

### ISSUE THREAD

**Issue by leoshcn** [archsocks/archsocks#3]
比如，数字是代表什么？不同等级的份数分别是什么意义等等。

谢谢

**Comment by archsocks** [comment]
速度0-50分，稳定性负分说明连接失败的数量，总分是加起来的分。
你不用管这个分数，这是调试用的。当前服务器会自动根据这个分来选择，你无法手动选。






Date: Sun, 8 May 2016 06:56:25 -0700
